# Generated by Django 4.1.5 on 2023-04-25 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='client.client'),
            preserve_default=False,
        ),
    ]
