# Generated by Django 4.1.5 on 2023-04-26 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_files_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='File',
        ),
    ]
