# Generated by Django 4.1.5 on 2023-04-26 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('client', '0004_rename_files_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='team.team'),
            preserve_default=False,
        ),
    ]
