# Generated by Django 4.1.5 on 2023-04-27 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_file_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='client.client'),
        ),
        migrations.AlterField(
            model_name='file',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents/%m/%d/%Y'),
        ),
    ]
