# Generated by Django 4.1.5 on 2023-04-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_file_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
