# Generated by Django 4.1.5 on 2023-04-28 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_client_pdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
