# Generated by Django 4.1.5 on 2023-03-29 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclusions', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Menu_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_items', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('quotation_owner', models.CharField(blank=True, max_length=255)),
                ('quotation_request_number', models.CharField(blank=True, max_length=255)),
                ('quotation_status', models.CharField(blank=True, choices=[('new', 'new'), ('accepted', 'accepted'), ('on_going', 'on_going'), ('completed', 'completed')], max_length=255)),
                ('quotation_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField(auto_now=True)),
                ('client_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='client.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=255)),
                ('unit', models.IntegerField(blank=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(blank=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10)),
                ('from_date', models.DateTimeField(auto_now_add=True)),
                ('to_date', models.DateField(auto_now=True)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.CharField(blank=True, max_length=255)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.FloatField(blank=True)),
                ('tax_amount', models.FloatField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('terms_and_condition', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('inclusions', models.ManyToManyField(blank=True, to='quote.inclusion')),
                ('menu_items', models.ManyToManyField(blank=True, to='quote.menu_item')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='quote.quote')),
            ],
        ),
    ]
