# Generated by Django 4.1.5 on 2023-03-29 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tax_amount',
        ),
    ]
