# Generated by Django 4.1.5 on 2023-03-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_remove_product_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_amount',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
    ]
