# Generated by Django 4.1.5 on 2023-03-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0006_alter_product_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='terms_and_condition',
        ),
        migrations.AddField(
            model_name='quote',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='discount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='sub_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='tax_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='terms_and_condition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
