# Generated by Django 4.1.5 on 2023-04-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0008_alter_quote_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
