# Generated by Django 4.1.5 on 2023-04-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0009_quote_is_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='is_accepted',
        ),
    ]
