# Generated by Django 4.1.5 on 2023-07-28 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio_Visual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_visuals', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateTimeField(blank=True, null=True)),
                ('check_out_date', models.DateTimeField(blank=True, null=True)),
                ('number_of_rooms', models.IntegerField(blank=True, null=True)),
                ('occupancy', models.CharField(blank=True, max_length=255, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('room_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('room_cgst_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('room_cgst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('room_sgst_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('room_sgst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Meal_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_plans', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(blank=True, max_length=255, null=True)),
                ('package_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('package_cgst_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('package_cgst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('package_sgst_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('package_sgst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Praposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('from_date', models.DateField(blank=True)),
                ('to_date', models.DateField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='praposals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_types', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SetUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_ups', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venues', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('min_attendance', models.IntegerField(blank=True, null=True)),
                ('max_attendance', models.IntegerField(blank=True, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('venue_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('miscellaneous_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('audio_visuals', models.ManyToManyField(blank=True, to='praposal.audio_visual')),
                ('praposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='praposal.praposal')),
                ('set_ups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='praposal.setup')),
                ('venues', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='praposal.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Praposal_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cgst_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cgst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sgst_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sgst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='praposal_invoices', to='praposal.booking')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='praposal_invoices', to='praposal.package')),
            ],
        ),
        migrations.CreateModel(
            name='Package_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_groups', to='praposal.service')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='praposal.service'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='praposal.package')),
            ],
        ),
        migrations.CreateModel(
            name='Forma_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_package', models.IntegerField(blank=True)),
                ('water_cleaning', models.IntegerField(blank=True)),
                ('security_deposite', models.IntegerField(blank=True)),
                ('grand_total', models.IntegerField(blank=True)),
                ('praposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forma_invoices', to='praposal.praposal')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_types', to='praposal.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='praposal.service'),
        ),
        migrations.CreateModel(
            name='Deposite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposite', models.CharField(blank=True, max_length=255)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('amount_due', models.CharField(blank=True, max_length=255)),
                ('praposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposites', to='praposal.praposal')),
            ],
        ),
        migrations.CreateModel(
            name='Default_Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_package_name', models.CharField(blank=True, max_length=255)),
                ('default_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('default_cgst_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('default_cgst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('default_sgst_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('default_sgst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('package_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defaults_package', to='praposal.package_group')),
            ],
        ),
        migrations.CreateModel(
            name='Default_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('default_quantity', models.IntegerField(blank=True, null=True)),
                ('default_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_items', to='praposal.default_package')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='meal_plans',
            field=models.ManyToManyField(blank=True, to='praposal.meal_plan'),
        ),
        migrations.AddField(
            model_name='booking',
            name='praposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='praposal.praposal'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_types',
            field=models.ManyToManyField(blank=True, to='praposal.room_type'),
        ),
    ]
