# Generated by Django 4.1.5 on 2023-08-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praposal', '0002_remove_default_item_default_package_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='default_package',
            name='default_package_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
