# Generated by Django 4.1.5 on 2023-08-01 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('praposal', '0003_default_package_default_package_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='default_package',
            name='default_package_rate',
        ),
    ]
