# Generated by Django 4.1.5 on 2023-08-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praposal', '0004_remove_default_package_default_package_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='option_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
