# Generated by Django 4.1.5 on 2023-08-03 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('praposal', '0006_choice_alter_item_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='package',
        ),
        migrations.AddField(
            model_name='choice',
            name='package',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='praposal.package'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='choices',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='praposal.choice'),
            preserve_default=False,
        ),
    ]
