# Generated by Django 4.1.5 on 2023-08-03 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('praposal', '0007_remove_item_package_choice_package_item_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='praposal.package'),
        ),
    ]
