# Generated by Django 4.1.5 on 2023-08-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praposal', '0008_alter_choice_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
