# Generated by Django 4.1.5 on 2023-08-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praposal', '0009_choice_choice_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
