# Generated by Django 4.1.5 on 2023-08-04 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('praposal', '0012_remove_package_group_service_service_package_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='package_group',
        ),
        migrations.AddField(
            model_name='package_group',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_groups', to='praposal.service'),
        ),
    ]
