# Generated by Django 4.1.5 on 2023-08-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praposal', '0015_alter_event_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='service',
        ),
        migrations.AddField(
            model_name='service',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='services', to='praposal.event'),
        ),
    ]
