# Generated by Django 4.1.5 on 2023-08-07 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('praposal', '0016_remove_event_service_service_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='praposal.service'),
        ),
    ]
