# Generated by Django 4.1.5 on 2023-08-07 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('praposal', '0017_remove_service_events_event_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='rate',
        ),
    ]
