# Generated by Django 4.1.5 on 2023-08-08 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('praposal', '0019_alter_event_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='service',
        ),
        migrations.AddField(
            model_name='service',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='praposal.event'),
        ),
        migrations.AddField(
            model_name='service',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='services', to='praposal.event_type'),
        ),
    ]
