# Generated by Django 4.1.5 on 2023-08-08 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('praposal', '0020_remove_event_service_service_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='praposal.event'),
        ),
        migrations.AlterField(
            model_name='service',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='services', to='praposal.event_type'),
        ),
    ]
