# Generated by Django 4.1.5 on 2023-08-08 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('praposal', '0021_alter_service_event_alter_service_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='event',
        ),
        migrations.RemoveField(
            model_name='service',
            name='event_type',
        ),
        migrations.AddField(
            model_name='event',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='praposal.service'),
        ),
    ]
