# Generated by Django 4.1.5 on 2023-08-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praposal', '0024_remove_event_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
